### PR TITLE
Ci Windows

### PR DESCRIPTION
**Pull request by p-groarke**
Adds AppVeyor CI for MSVC 2017.

As with travis CI, this will require an AppVeyor account. I will update the badge once we get it.

### CODE REVIEW

**Comment by p-groarke** [comment]
Sounds good to me. Let me know when things are sorted out.

**Comment by p-groarke** [comment]
Any ETA on this?

**Comment by TBBle** [comment]
No movement I'm aware of. I'll ping @hatcat directly, since I expect he knows from what to do about the username/password, since I believe he was involved in the email address setup for this Github organisation.

**Comment by p-groarke** [comment]
I can't help but feel this is being ignored due to SG14's disinterest in supporting MSVC. This is yet another example where gaming is being ignored. These libraries **have** to compile on Visual Studio if you wish to cater to the gaming industry.

MSVC 2017's C++ support has come a long way, it is now a compliant compiler. I don't see any reason why this shouldn't be prioritized.

**Comment by Quuxplusone** [comment]
@p-groarke: I think it's likely more about AppVeyor being less user-friendly than Travis (especially for "organizations" as opposed to individuals). If TravisCI supported `os: windows`, I think we'd adopt it in a heartbeat.

**Comment by ThomasFeher** [comment]
Seems like it is already available: https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by p-groarke** [comment]
Just a FIY, you still aren't compiling with MSVC on Windows XD

**Comment by Quuxplusone** [comment]
@p-groarke: Aren't we? https://travis-ci.org/WG21-SG14/SG14/jobs/482637464 But I do know this is x32, not x64. Pull requests from someone who knows more about Travis and/or MSVC than I do will be speedily merged. ;)

**Comment by Quuxplusone** [comment]
@p-groarke: But if you scroll down to where CMake is doing its thing, you see

```
$ mkdir build && cd build && cmake .. && cmake --build . && ./bin/sg14_tests
-- Building for: Visual Studio 15 2017
-- The CXX compiler identification is MSVC 19.16.27023.1
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
```

etc. I think CMake is "correctly" picking up MSVC even though Travis might not have expected it to.

**Comment by p-groarke** [comment]
@Quuxplusone I think you're right. Thats good to hear :) I'll send a x64 PR soon.

**Pull request closed without merging**
